var mongoose = require('mongoose'),
Schema = mongoose.Schema;

var CardSchema = new Schema({
    artist: String,
    borderColor: String,
    colorIdentity: Array,
    colors: Array,
    convertedManaCost: Number,
    flavorText: String,
    foreignData: Array,
    frameVersion: String,
    hasFoil: Boolean,
    hasNonFoil: Boolean,
    layout: String,
    legalities: Object,
    manaCost: String,
    multiverseId: Number,
    name: String,
    number: String,
    originalText: String,
    originalType: String,
    power: String,
    printings: Array,
    rarity: String,
    rulings: Array,
    scryfallId: String,
    scryfallIllustrationId: String,
    scryfallOracleId: String,
    subtypes: Array,
    supertypes: Array,
    tcgplayerProductId: Number,
    tcgplayerPurchaseUrl: String,
    text: String,
    toughness: String,
    type: String,
    types: Array,
    uuid: String,
    uuidV421: String,
    core_imageLink: String,
    core_fallbackLinks: Array,
    core_set: String
}, { collection: 'cards' });

module.exports = CardSchema;